#import "../template.typ": *

// Take a look at the file `template.typ` in the file panel
// to customize this template and discover how it works.
#show: project.with(
  title: "Math 542 HW2",
  authors: ("Hongtao Zhang",),
)

#let (
  theorem,
  lemma,
  corollary,
  remark,
  proposition,
  example,
  proof
) = (
  theorem,
  lemma,
  corollary,
  remark,
  proposition,
  example,
  proof
)

#show: thm-rules


= Chinese Remainder

== 10.3.16 <10.3.16>

For any left ideal $I$ of $R$ define
$
    I M = {sum_"finite" a_i m_i | a_i in I, m_i in M}
$
to be the collection of all finite sums of elements of the form $a m$ where $a in I$ and $m in M$. This is a submodule of $M$.

For any ideal $I$ of $R$ let $I M$ be the submodule defined above. Let $A_1, ..., A_k$ be any ideals in the ring $R$. Prove that the map

$ phi : M -> M/(A_1 M) times ... times M/(A_k M) "defined by" m arrow.bar (m + A_1 M, ..., m + A_k M) $

is an $R$-module homomorphism with kernel $A_1 M sect A_2 M sect ... sect A_k M$.

#proof[
    Want to check $forall x, y in M : phi(x+y) = phi(x) + phi(y)$ and $forall x in M, r in R: phi(r x) = r phi(x)$.

    $forall x,y in M: phi(x+y) &= (x + y + A_1 M, ..., x + y + A_k M) \
        &= (x + A_1 M, ..., x + A_k M) + (y + A_1 M, ..., y + A_k M) \
        & = phi(x) + phi(y)$

    $forall r in R, x in M: phi(r x) = (r x A_1M, ..., r x A_k M) = r(x A_1 M,..., x A_k M)$ because submodule is invariant under the ring $R$.

    To become the kernel, it need to satisfy that $forall i in [1,k] : x+A_i M = A_i M$, which implies that $x in sect.big_i A_i M$.
]

== 10.3.17

In the notation of the @10.3.16, assume further that the ideals $A_1, ..., A_k$ are pairwise comaximal $(i.e. forall i != j : A_i + A_j = R)$. Prove that

$
    M/((A_1, ..., A_k) M) cong M/(A_1 M) times ... times M/(A_k M)
$

[See proof of the Chinese Remainder Theorem for rings in Section 7.6.]

#proof[
    Based on the proof of Chinese Remainder Theorem for rings in Section 7.6, it suffices to check the case when $k = 2$.

    Consider a map $phi : M -> M/(A_1 M) times M/(A_2 M)$ by sending $x arrow.bar (a + A_1M, a+A_2M)$.

    $phi$ is a module homomorphism based on @10.3.16. 

    It is surjective because 
]

= Fractions

Suppose that $R$ is an integral domain and let $M$ be an $R$-module. Let $S$ be a multiplicatively closed subset of $R$ that includes $1$ and does not include $0$ (for instance complemenets of prime ideals). Let $S^(-1) M$ be the collection of symbols of the form $m/s$ where $m in M$ and $s in S$ and where we insist that $(s' dot m)/(s's) = m/s$ for any $s' in S$. This is an abelian group where we define addition by $m_1/s_1 + m_2/s_2 := (s_2 dot m_1 + s_1 dot m_2)/(s_1s_2)$ for $m_1, m_2 in M$ and $s_1, s_2 in S$. Note that $S^(-1)R$ is a ring if we additionally define multiplication by $r_1/s_1 dot r_2/s_2 := (r_1r_2)/(s_1s_2)$ for $r_1, r_2 in R$ and $s_1, s_2 in S$. Finally, we note that $S^(-1)M$ is an $S^(-1)R$-module where $r/(s_1) dot m/s_2 := (r dot m)/(s_1s_2)$.

== 

Show that if $f : M_1 → M_2$ is a homomorphism of R-modules,
then the map $S^(-1)f : S^(-1)M_1 → S^(-1)M_2$ sending $m/s arrow.bar f(m)/s$
is a
homomorphism of $S^(-1)R$ modules.

#let inv(x) = $#x^(-1)$

#proof[
  Given that $f$ is a homomorphism of $R$-module, this question is automatically right when checking addition and multiplication.

  $
    forall m/s in S^(-1)M_1, r in R: inv(S)f(r m/s) = f(r m)/s = (r f(m))/s 
  $

  addition is similar and omitted.
]

==

#let tensor = $times.circle$

#proof[

]

==

#proof[

]

= Tensor

== 10.4.2

Show that the element "$2 times.circle 1$" is $0 in ZZ times.circle_ZZ ZZ/(2ZZ)$ but is nonzero in $2ZZ times.circle_ZZ ZZ/(2ZZ)$.

#proof[
  Use the small lemma in class, we have $A tensor ZZ/(n ZZ)$ = $A/(n A)$.

  Then $ZZ tensor ZZ/(2ZZ) = ZZ/(2ZZ)$

  $2ZZ tensor ZZ/(2ZZ) = (2ZZ)/(2 dot 2ZZ) = $



]

== 10.4.20

Let $I = (2,x)$ be the ideal generated by $2$ and $x$ in the ring $R = ZZ[x]$. Show that the element $2 tensor 2+x tensor x$ in $I tensor_R I$ is not a simple tensor, i.e. cannot be written as $a tensor b$ for some $a,b in I$.

= Duality

Suppose that $R$ is commutative. Let $M, N$, and $U$ be $R$-modules. The _dual module_ of M is defined to be $M^* := "Hom"_R (M, R)$.

==

Suppose that $(e_1, ..., e_n)$ is a bisis, i.e. linearly independent spanning set for $M$. Define $e_i^* in M^*$ to be the homomorphism that sends $e_i$ to $1$ and all other $e_j (j != i)$ to $0$. Show that $(e_1^*,...,e_n^*)$ is a basis for $M^*$.

==

Show that if $M$ is a free $R$-module of rank $n$, where $n$ is a positive integer, then $(M^*)^*$ is isomorphic to $M$. (Hint: Consider the map $M arrow.long (M^*)^*$ that sends $m in M$ to $"ev"_m$ where $"ev"_m : M^* -> R$ sends a homomorphism $phi : M -> R$ to $phi(m)$. To establish that this map is a surjection show that, in the notation of the preceding part, $((e_i)^*)^* = "ev"_e_i$.)

==

Show that if $R$ is a field and $M$ and $N$ are finitely generated, then $"Hom"_R (M, N) cong M^* tensor N$ as $R$-modules. Show that there is not necessarily such an isomorphism when $R=ZZ$ and $M$ and $N$ are finitely generated $ZZ$-modules.

= Counterexample

Do one of the following two problems: 10.3.24 or 10.3.26.

== 10.3.24

For each positive integer $i$ let $M_i$ be the free $ZZ$-module $ZZ$, and let $M$ be the direct product $product_(i in Z^+) M_i$. Each elements of $M$ is in the uniquely determined form $(a_1, a_2, a_3, ...)$ with $a_i in ZZ$ for all $i$. Let $N$ be the submodule of $M$ consisting of all such tuple with only finitely many nonzero $a_i$. Assume $M$ is a free $ZZ$-module with basis $cal(B)$.

===

Show that $N$ is countable.

#proof[
  It suffices to prove that the diagnoal argument that proves $RR$ is uncountable does not work here.

  Because all elements in $N$ contains only finitely many nonzero entries, the new element we retrieve from the diagonal plus 1 can only contain finitely many nonzero entries. However, this is not possible unless we have $9$ on the diagonal after some finitely many terms.

  However, that contradicts to how we enumerate the elements in $N$. Thus the diagnol plus 1 is not in $N$.
]

===

Show that there is some countable subset $cal(B)_1$ of $cal(B)$ such that $N$ is contained in the submodule, $N_1$, generated by $cal(B)_1$. Show also that $N_1$ is countable.

#proof[
  
]